### ISSUE TITLE
CHANGELOG and README files

### ISSUE THREAD

**Issue by rafamizes** [dartoos-dev/eo_color#2]
**CHANGELOG**
- The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)

**README**

**Comment by 0pdd** [comment]
@rafamizes 3 puzzles [#5](https://github.com/dartoos-dev/eo_color/issues/5), [#6](https://github.com/dartoos-dev/eo_color/issues/6), [#7](https://github.com/dartoos-dev/eo_color/issues/7) are still not solved.

**Comment by 0pdd** [comment]
@rafamizes 2 puzzles [#5](https://github.com/dartoos-dev/eo_color/issues/5), [#6](https://github.com/dartoos-dev/eo_color/issues/6) are still not solved; solved: [#7](https://github.com/dartoos-dev/eo_color/issues/7).

**Comment by 0pdd** [comment]
@rafamizes all 3 puzzles are solved here: [#5](https://github.com/dartoos-dev/eo_color/issues/5), [#6](https://github.com/dartoos-dev/eo_color/issues/6), [#7](https://github.com/dartoos-dev/eo_color/issues/7).
