### ISSUE TITLE
Primaries swatch

### ISSUE THREAD

**Issue by rafamizes** [dartoos-dev/eo_color#24]
The material design primary color swatches, excluding grey.
[primaires](https://api.flutter.dev/flutter/material/Colors/primaries-constant.html)

**Comment by 0pdd** [comment]
@rafamizes 3 puzzles [#32](https://github.com/dartoos-dev/eo_color/issues/32), [#33](https://github.com/dartoos-dev/eo_color/issues/33), [#34](https://github.com/dartoos-dev/eo_color/issues/34) are still not solved.

**Comment by 0pdd** [comment]
@rafamizes all 3 puzzles are solved here: [#32](https://github.com/dartoos-dev/eo_color/issues/32), [#33](https://github.com/dartoos-dev/eo_color/issues/33), [#34](https://github.com/dartoos-dev/eo_color/issues/34).
